// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'process.env.apiKey.w',
    appId: 'process.env.appId.w',
    messagingSenderId: 'process.env.messagingSenderId.w',
    projectId: 'process.env.projectId.w',
    authDomain: 'process.env.authDomain.w',
    storageBucket: 'process.env.storageBucket.w',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'process.env.apiKey.a',
    appId: 'process.env.appId.a',
    messagingSenderId: 'process.env.messagingSenderId.a',
    projectId: 'process.env.projectId.a',
    storageBucket: 'process.env.storageBucket.a',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'process.env.apiKey.i',
    appId: 'process.env.appId.i',
    messagingSenderId: 'process.env.messagingSenderId.i',
    projectId: 'process.env.projectId.i',
    storageBucket: 'process.env.storageBucket.i',
    iosBundleId: 'process.env.iosBundleId.i',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'process.env.apiKey.m',
    appId: 'process.env.appId.m',
    messagingSenderId: 'process.env.messagingSenderId.m',
    projectId: 'process.env.projectId.m',
    storageBucket: 'process.env.storageBucket.m',
    iosBundleId: 'process.env.iosBundleId.m',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'process.env.apiKey.ws',
    appId: 'process.env.appId.ws',
    messagingSenderId: 'process.env.messagingSenderId.ws',
    projectId: 'process.env.projectId.ws',
    authDomain: 'process.env.authDomain.ws',
    storageBucket: 'process.env.storageBucket.ws',
  );
}
