// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzhEAvVWntyPAEpaOc08dLJ5QaGAwA_c',
    appId: '1:753329806297:web:63ce2340acc4844f9657c8',
    messagingSenderId: '753329806297',
    projectId: 'myreal-app-4ac73',
    authDomain: 'myreal-app-4ac73.firebaseapp.com',
    storageBucket: 'myreal-app-4ac73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDnig2LaDPjNXhqL1BUqDPfWUwcjJtlo4',
    appId: '1:753329806297:android:05477be626ea9fa19657c8',
    messagingSenderId: '753329806297',
    projectId: 'myreal-app-4ac73',
    storageBucket: 'myreal-app-4ac73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdFHfBk4F45RE7tQmKQtZzCC6UqTCeL4',
    appId: '1:753329806297:ios:9a7f0ccf1dc32cb09657c8',
    messagingSenderId: '753329806297',
    projectId: 'myreal-app-4ac73',
    storageBucket: 'myreal-app-4ac73.firebasestorage.app',
    iosBundleId: 'com.example.myrealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdFHfBk4F45RE7tQmKQtZzCC6UqTCeL4',
    appId: '1:753329806297:ios:9a7f0ccf1dc32cb09657c8',
    messagingSenderId: '753329806297',
    projectId: 'myreal-app-4ac73',
    storageBucket: 'myreal-app-4ac73.firebasestorage.app',
    iosBundleId: 'com.example.myrealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZzhEAvVWntyPAEpaOc08dLJ5QaGAwA_c',
    appId: '1:753329806297:web:7fa866c0d98a7c2e9657c8',
    messagingSenderId: '753329806297',
    projectId: 'myreal-app-4ac73',
    authDomain: 'myreal-app-4ac73.firebaseapp.com',
    storageBucket: 'myreal-app-4ac73.firebasestorage.app',
  );
}
